### ISSUE TITLE
Adapters out of reach - Interstitial not working anymore

### ISSUE THREAD

**Issue by paulstelzer** [charlesbodman/cordova-plugin-ironsource-ads#11]
Hello guys, 
since 18 April, 2018 my iOS app has no more interstitial impressions (on ironsource it is 0). I am using mediation where Unity, Admob und Ironsource are integrated. I did not update the app since then, so from one day to another it is not working anymore.

I take a look at Xcode, debug my app and the problem is "Adapters out of reach". Then I updated the SDK from Ironsource, but still "Adapters out of reach". Is it a problem with this Cordova Plugin which should be updated or has Ironsource Mediation a problem? This only occurs on iOS! I contacted Ironsource, but as I know their support, it will need days until they answer.

PS: Rewarded Videos is still working, only interstital is not working

**Comment by Superprogrameur59** [comment]
Hello,

I have almost the same problem, my integration was working fine and now I can't initialize the SDK ( so I cant't show ads or offerwall).

I tested my application with another app_key (4ea90fad), the one given in test by Ironsource. With this one everything works correctly.

So I think there's something to configure on the Ironsource platform but I don't know what...

If I get some news, I'll tell you

**Comment by charlesbodman** [comment]
Sorry for the late response. 
I'll take a look and run some tests.

**Comment by charlesbodman** [comment]
For right now i'v just updated IronSource to the latest for IOS and Android. 

Looking at my production apps. There has not been a decline in impressions, so I would think that it's most likely a problem on the IronSource end. I'll do more testing on my example app tonight and get some more information. 

https://github.com/charlesbodman/cordova-plugin-ironsource-ads/commit/9665ca3eff2ed7ebc7f6c508c762d9063a0fcaff

**Comment by paulstelzer** [comment]
Very strange, I already using the latest versions of ironsource sdk and mediation sdks, but on IOS he is saying "Adapters out of reach". I still waiting for an answer of the Ironsource support (their support is very bad)

**Comment by Superprogrameur59** [comment]
Thank you for update.

I still can't initialise the sdk with my personal app_key : 7048f325, but it's possible with demo key : 4ea90fad (my app is configured in test mode, not live).

As you said it's probably an Ironsource's issue. I am waiting for their answer.

**Comment by paulstelzer** [comment]
It has to do with Ironsource, something went really wrong at their end. So it's not this cordova plugin (as we already expected). But they are not answering me (very bad service). So I switched to Admob Mediation, there is everything  working fine.
