### ISSUE TITLE
Error cordova build

### ISSUE THREAD

**Issue by hldevup** [charlesbodman/cordova-plugin-ironsource-ads#16]
Hello,
while launching cordova i get this error 

`3 actionable tasks: 2 executed, 1 up-to-date
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':debugCompileClasspath'.
> Could not find com.ironsource.sdk:mediationsdk:6.7.12.0.
  Searched in the following locations:
      file:/C:/Users/HDSKTPL-PC/AppData/Local/Android/Sdk/extras/m2repository/com/ironsource/sdk/mediationsdk/6.7.12.0/mediationsdk-6.7.12.0.pom
      file:/C:/Users/HDSKTPL-PC/AppData/Local/Android/Sdk/extras/m2repository/com/ironsource/sdk/mediationsdk/6.7.12.0/mediationsdk-6.7.12.0.jar
      file:/C:/Users/HDSKTPL-PC/AppData/Local/Android/Sdk/extras/google/m2repository/com/ironsource/sdk/mediationsdk/6.7.12.0/mediationsdk-6.7.12.0.pom
      file:/C:/Users/HDSKTPL-PC/AppData/Local/Android/Sdk/extras/google/m2repository/com/ironsource/sdk/mediationsdk/6.7.12.0/mediationsdk-6.7.12.0.jar
      file:/C:/Users/HDSKTPL-PC/AppData/Local/Android/Sdk/extras/android/m2repository/com/ironsource/sdk/mediationsdk/6.7.12.0/mediationsdk-6.7.12.0.pom
      file:/C:/Users/HDSKTPL-PC/AppData/Local/Android/Sdk/extras/android/m2repository/com/ironsource/sdk/mediationsdk/6.7.12.0/mediationsdk-6.7.12.0.jar
      https://jcenter.bintray.com/com/ironsource/sdk/mediationsdk/6.7.12.0/mediationsdk-6.7.12.0.pom
      https://jcenter.bintray.com/com/ironsource/sdk/mediationsdk/6.7.12.0/mediationsdk-6.7.12.0.jar
      https://maven.google.com/com/ironsource/sdk/mediationsdk/6.7.12.0/mediationsdk-6.7.12.0.pom
      https://maven.google.com/com/ironsource/sdk/mediationsdk/6.7.12.0/mediationsdk-6.7.12.0.jar
      https://adcolony.bintray.com/AdColony/com/ironsource/sdk/mediationsdk/6.7.12.0/mediationsdk-6.7.12.0.pom
      https://adcolony.bintray.com/AdColony/com/ironsource/sdk/mediationsdk/6.7.12.0/mediationsdk-6.7.12.0.jar
      https://dl.bintray.com/ironsource-mobile/android-sdk/com/ironsource/sdk/mediationsdk/6.7.12.0/mediationsdk-6.7.12.0.pom
      https://dl.bintray.com/ironsource-mobile/android-sdk/com/ironsource/sdk/mediationsdk/6.7.12.0/mediationsdk-6.7.12.0.jar`
Any help please ?

**Comment by charlesbodman** [comment]
Fixed, 
https://github.com/charlesbodman/cordova-plugin-ironsource-ads/commit/518b4f1882fc565b171e04dacf5f2989294c875f

Give it another shot.
