### ISSUE TITLE
Class EBanner  deprecata

### ISSUE THREAD

**Issue by mforloni** [charlesbodman/cordova-plugin-ironsource-ads#17]
Hi there is an error compile.
The import class "import com.ironsource.mediationsdk.EBannerSize;" not work. Probably is deprecated.
I think the new class is "import com.ironsource.mediationsdk.ISBannerSize;"
Could you correct it?

Thank you so much for the good work

**Comment by mforloni** [comment]
In addition I have installed the plugin with "npm i cordova-plugin-ironsource-ads-ka" not with "npm i cordova-plugin-ironsource-ads". With "npm i cordova-plugin-ironsource-ads" the application crash on the start.

**Comment by charlesbodman** [comment]
Ah okay, 'cordova-plugin-ironsource-ads-ka' is our internal version. 
I'll try to take a look at it this week, and fix it. I need to finish implementing the banners anyways.

**Comment by DennisNicolas** [comment]
Hi, any news on this?

**Comment by mforloni** [comment]
One question! Why i don't recive reward with event "offerwallCreditReceived". I don't understand.

**Comment by CharlieBodman** [comment]
@DennisNicolas , I haven't had time to finish up this. Scheduling some time soon. Definitely accepting pull requests.

**Comment by charlesbodman** [comment]
I'm going to be working on this today.

**Comment by mforloni** [comment]
Thanks ;)

**Comment by charlesbodman** [comment]
Updated to 0.1.11 [e09b3070f4994f1d41a8ce59f5e82815ad66909a]

**Here is a demo project**
https://github.com/charlesbodman/cordova-plugin-ironsource-ads-demo

Let me know if you need help with anything. The banner support is limited.

**Comment by mforloni** [comment]
Thanks a  lot. I have tried the new version. The banner work now. I don't receveid the credit from Offerwall. The event "offerwallCreditReceived" not work only the "offerwallClosed" event. The configuration on my iron dashboard is correct. Could you help me? What should i check?

**Comment by mforloni** [comment]
Work!!
