### ISSUE TITLE
Error while launching cordova build

### ISSUE THREAD

**Issue by quig** [charlesbodman/cordova-plugin-ironsource-ads#4]
Hi Charles,

I got the following output after launching `cordova build` with the plugin:

![cordova_build](https://user-images.githubusercontent.com/3135312/32959135-88590696-cbb8-11e7-90e5-6b49ee460a73.png)

Here are my env info:

![info](https://user-images.githubusercontent.com/3135312/32959147-959f9bf8-cbb8-11e7-909a-30a36d06dae6.png)

It looks to be a version compaibility issue, do you have an idea of what I should change ?

Thanks,

**Comment by charlesbodman** [comment]
I'll take a look.

**Comment by charlesbodman** [comment]
What ad networks are you planning on using? 

Iv just pushed a fix to remove unused permissions. (as well as a banner fix)

**Comment by quig** [comment]
Yep it works, I removed all networks I am not using from the plugin.xml and rebuild my app.

I did it manually since the last update of the plugin gave me the following error:

![error0 0 18](https://user-images.githubusercontent.com/3135312/32979311-c16680fc-cc4a-11e7-86fd-d6f2f2c3b9d5.png)

I am actually trying to display the offerwall, I do not know if it related to the plugin but the following snippet : 

```
IronSourceAds.showOfferwall({
    placement: "mydefaultplacement",
    onSuccess: function () {console.log('OK'); },
    onFailure: function (error) { console.log(error);}
});
```
does not display the offerwall, instead I got

> JSON error

as output of my console log. I've tried to debug it using android debug bridge but I see nothing abnormal. Is the offerwall working correctly for you ?

**Comment by charlesbodman** [comment]
I'll take a look.

**Comment by charlesbodman** [comment]
Fixed, it works as expected now. 

Forgot to pass in placement name in the Js api. View commit for changes.

**Comment by quig** [comment]
Thanks for the fix but although I do not see any errors in my logs, the Offerwall gives me a white screen.  I wonder if this is coming from my implementation or ironsource configuration.

Here is my code 
```
       function displayOfferWall(){
                if (window.IronSourceAds) {
                    window.IronSourceAds.setDynamicUserId({
                        userId: vm.currentUser.id
                    });
                    window.IronSourceAds.showOfferwall();
                }
        }

```
_Since this is not related to the issue, do you want me to close this one and open a new ?_

**Comment by charlesbodman** [comment]
Javascript looks okay, 

I'll verify with setDynamicUserId, might be something with that. 

Ya, lets open a new issue.
