### ISSUE TITLE
showOfferwall displays a white screen

### ISSUE THREAD

**Issue by quig** [charlesbodman/cordova-plugin-ironsource-ads#5]
This issue follows the discussion started [here](https://github.com/charlesbodman/cordova-plugin-ironsource-ads/issues/4).

As this might be linked to my implementation or ironsource configuration, I've tried with this [plugin](https://github.com/Dexus/cordova-plugin-ironSource) and it works correctly except the offerwall does not reopen once closed.

Here is the code:

```
function displayOfferWall(){
                if (window.IronSourceAds) {
                    window.IronSourceAds.setDynamicUserId({
                        userId: vm.currentUser.id
                    });
                    window.IronSourceAds.showOfferwall();
                }
        }

```

and my info : 

![image](https://user-images.githubusercontent.com/3135312/32989236-5c33ba18-cd0a-11e7-9067-00dafd283c24.png)

**Comment by charlesbodman** [comment]
I tested it, it seems to work fine. 

I looked at what @Dexus had. It's pretty much the same call. It's a simple API. The biggest difference is the IronSource framework is the newest version here. 

I'll look into it further. 
I wonder if it's something to with the iconic framework.

**Comment by Dexus** [comment]
Hi,

It looks like the Ionic Framework breaks in the last time many plugins.

Do you have the options to debug live with chrome and looking about js errors or the debug output of the android studio?

Then i can help maybe a bit more. I can‘t find currently any error or bug with default browser or crosswalk.

Regards
Josef

Von meinem iPhone gesendet

**Comment by charlesbodman** [comment]
@quig what device are you testing on

**Comment by quig** [comment]
Hi,

Sorry for the late reply.

I usually work on my HTC One m7 (Android 5.0.2) and still don't see the offerwall. However, I just tried using a Samsung S8 on Genymotion and it works oO. 

Wonder if it is related to the device...

**Comment by Dexus** [comment]
@quig can you please check what browser engine the HTC is using by default with ionic? and can you try to use crosswalk to check if the problem exist on both browser engines?

**Comment by quig** [comment]
Hi,

Sorry for the inconvenience, it seems the issue was coming from my code, it now works fine on the different devices I am using including the HTC One m7. The plugin works well, thanks for your work.

_Note_: I was already using crosswalk actually

>     <plugin name="cordova-plugin-crosswalk-webview" spec="~2.3.0">
>         <variable name="XWALK_VERSION" value="23+" />
>         <variable name="XWALK_LITEVERSION" value="xwalk_core_library_canary:17+" />
>         <variable name="XWALK_COMMANDLINE" value="--disable-pull-to-refresh-effect" />
>         <variable name="XWALK_MODE" value="embedded" />
>         <variable name="XWALK_MULTIPLEAPK" value="true" />
>     </plugin>
>

**Comment by charlesbodman** [comment]
Glad you figured it out @quig :) 👍
