### ISSUE TITLE
interstitialFailedToLoad triggered each time in live mode

### ISSUE THREAD

**Issue by tscislo** [charlesbodman/cordova-plugin-ironsource-ads#9]
I managed to work with you plugin to show ads in test mode however in live mode I always get interstitialFailedToLoad error.  Is there something I'm doing wrong?

Here is what I do:

```
                IronSourceAds.init({
                    appKey: "xxx"
                });

                    window.addEventListener("interstitialLoaded", function () {
                        IronSourceAds.showInterstitial();
                    });
                    window.addEventListener("interstitialFailedToLoad", function (e) {
                        console.warn('unable to load interstitial', e) // this gets always triggered!
                        innerCallback();
                    });
                    IronSourceAds.loadInterstitial();
                    window.addEventListener("interstitialShown", innerCallback);
                    window.addEventListener("interstitialShowFailed", innerCallback);
```

**Comment by tscislo** [comment]
validateIntegration() result:

```
02-28 21:12:27.663 29002-29002/? I/IntegrationHelper: Verifying Integration:
02-28 21:12:27.663 29002-29002/? W/IntegrationHelper: --------------- IronSource --------------
02-28 21:12:27.663 29002-29002/? I/IntegrationHelper: *** Permissions ***
02-28 21:12:27.665 29002-29002/? I/IntegrationHelper: android.permission.INTERNET - VERIFIED
02-28 21:12:27.666 29002-29002/? I/IntegrationHelper: android.permission.ACCESS_NETWORK_STATE - VERIFIED
02-28 21:12:27.666 29002-29002/? I/IntegrationHelper: *** Activities ***
02-28 21:12:27.673 29002-29002/? I/IntegrationHelper: com.ironsource.sdk.controller.ControllerActivity - VERIFIED
02-28 21:12:27.677 29002-29002/? I/IntegrationHelper: com.ironsource.sdk.controller.InterstitialActivity - VERIFIED
02-28 21:12:27.679 29002-29002/? I/IntegrationHelper: com.ironsource.sdk.controller.OpenUrlActivity - VERIFIED
02-28 21:12:27.680 29002-29002/? W/IntegrationHelper: >>>> IronSource - VERIFIED
```

**Comment by charlesbodman** [comment]
Hi @tscislo , sorry for the late response. 

Which ad networks are you planning on using?

**Comment by tscislo** [comment]
Well, basically at first I'd like to get ads from IronSource and then add other adapters, however currently besides the test ad I was not able to see any ad...

**Comment by charlesbodman** [comment]
Yeah, I don't know if it will work without other mediation networks. I have not tried this. I too only see demo ads when testing just IronSource. It could be that they don't have Inventory or they require other mediators. 

I would contact IronSource and Inquire about that if all else fails.

**Comment by tscislo** [comment]
I contacted IronSource, but there was no concrete answer... at first I thought it was a problem with the plugin, but now I can clearly see that they have no fills... In that case what other ad providers besides AdMob, as a mediation network do you recommend? I tried AppLovin and InMobi integration and I cannot see any ads either.
Thanks!

**Comment by charlesbodman** [comment]
@tscislo , facebook ads. unity ads seem to work well.
